### ISSUE TITLE
Helm Chart SSl CA Cert Setup

### ISSUE THREAD

**Issue by flashpixx** [burakince/mlflow#139]
Hello,

I try to configure within the Helm Chart the LDAPS with an own CA cert, see #136 
I have got a cert-manager generated CA cert with `ca.cert`, `tls.key` and `tls.value`, but if i set `externalSecretForTrustedCACertificate: "my-ca"` it does not mount it correctly.

A common way to mount secrets is that I can append a volume and volumeMount add manually to the chart e.g.
```
    volumeMounts:
        - name: ca-cert
          mountPath: /mycerts
          readOnly: true
    volumes:
        - name: ca-cert
          secret:
            secretName: my-ca
            items:
                - key: ca.crt
                  path: ca.pem
```

I think this could be better, because it allow more control to mount it and it decouple the cert generating of the cert usage. So the file `trusted_ca_cert_secret.yaml` in the chart can be removed, because it can be assumed that the secret exist.

Thanks a lot

**Comment by burakince** [comment]
Hi @flashpixx 

We already use [volume](https://github.com/community-charts/helm-charts/blob/abbd694f1dade2566a7474a7dba1824e44b3c7d6/charts/mlflow/templates/deployment.yaml#L238-L241) and [volumeMounts](https://github.com/community-charts/helm-charts/blob/abbd694f1dade2566a7474a7dba1824e44b3c7d6/charts/mlflow/templates/deployment.yaml#L195-L200) definitions. Yes, chart has a problem but it's not related to the code. We used same `/etc/mlflow/auth` folder for our ini file before and having another volumeMount definition in the same folder created a problem. Basically, my folder selection was completely wrong. I just fixed that problem and already published [newest version of the chart](https://github.com/community-charts/helm-charts/releases/tag/mlflow-0.14.1).

I will show step by step how can I set test CA certificate from my local to mlflow container.

First my ca.crt file must have exactly `ca.crt` name. This is very important. If your CA certificate uses different name, just change it to `ca.crt` name and use the following command to create the secret.

```bash
kubectl create secret generic my-ca-secret --from-file=ca.crt --namespace=mlflow
```

<img width="783" alt="Image" src="https://github.com/user-attachments/assets/70aebbd2-18ad-4b56-ad05-6bcd82a4a91b" />

You can confirm secret is already created.

<img width="1205" alt="Image" src="https://github.com/user-attachments/assets/14dcea74-b8cb-473b-a942-ab005934afa6" />

And if you decode the secret, you must see your original certificate. For the test CA in my setup, it looks like:

<img width="750" alt="Image" src="https://github.com/user-attachments/assets/1a8a27bc-7985-4eb9-a50b-eddefed47c70" />

And when you use the configuration similar to below;

```yaml
ldapAuth:
  enabled: true
  uri: "ldap://lldap:3890/dc=mlflow,dc=test"
  tlsVerification: required
  lookupBind: "uid=%s,ou=people,dc=mlflow,dc=test"
  groupAttribute: "dn"
  searchBaseDistinguishedName: "ou=groups,dc=mlflow,dc=test"
  searchFilter: "(&(objectclass=groupOfUniqueNames)(uniquemember=%s))"
  adminGroupDistinguishedName: "cn=test-admin,ou=groups,dc=mlflow,dc=test"
  userGroupDistinguishedName: "cn=test-user,ou=groups,dc=mlflow,dc=test"
  externalSecretForTrustedCACertificate: "my-ca-secret"
```

You can connect to container and see certificate must be under `/certs` folder

<img width="565" alt="Image" src="https://github.com/user-attachments/assets/d751ae6c-8f7d-4485-8674-efc3a300e285" />

We only use `trusted_ca_cert_secret.yaml` file for `ldapAuth.encodedTrustedCACertificate` variable if they want to set self-signed CA certificate together with helm chart. But one or another, they are optional. If you don't want to set it with base64 encoded version of self-signed CA certificate from values.yaml file, you can just ignore it.

I hope this explanation could be useful. Could you please test newest version of chart and share your feedback here?

Thank you so much.

Best,
Burak
